# version: "3.8"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Sync local code with the container
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=opiyo123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: